"""add additional columns

Revision ID: 5aa8d18e376c
Revises: e79ff2d82986
Create Date: 2023-10-29 11:05:36.677513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa8d18e376c'
down_revision: Union[str, None] = 'e79ff2d82986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('start_date', sa.String(), nullable=False))
    op.add_column('tournament', sa.Column('end_date', sa.String(), nullable=False))
    op.add_column('tournament', sa.Column('city', sa.String(), nullable=False))
    op.add_column('tournament', sa.Column('sponsor_link', sa.String(), nullable=False))
    op.add_column('tournament', sa.Column('prize_pool', sa.Integer(), nullable=False))
    op.add_column('tournament', sa.Column('volume', sa.Float(), nullable=False))
    op.drop_column('tournament', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tournament', 'volume')
    op.drop_column('tournament', 'prize_pool')
    op.drop_column('tournament', 'sponsor_link')
    op.drop_column('tournament', 'city')
    op.drop_column('tournament', 'end_date')
    op.drop_column('tournament', 'start_date')
    # ### end Alembic commands ###
