"""add missing columns

Revision ID: e79ff2d82986
Revises: c36f6aff3059
Create Date: 2023-10-29 03:07:36.132944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e79ff2d82986'
down_revision: Union[str, None] = 'c36f6aff3059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('league', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('main_referee', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('fraction', sa.String(), nullable=False),
    sa.Column('referee', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tournaments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tournaments_pkey')
    )
    op.drop_table('tournament')
    # ### end Alembic commands ###
